"""add topic simplified_content

Revision ID: 2ebb030945e1
Revises: d5db9058740b
Create Date: 2026-08-24 10:23:46.022354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ebb030945e1'
down_revision = 'd5db9058740b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('simplified_content', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.drop_column('simplified_content')

    # ### end Alembic commands ###
