"""add breaks, coach chat, quiz safety

Revision ID: f8927df279cf
Revises: 2ebb030945e1
Create Date: 2026-08-25 01:54:03.687720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8927df279cf'
down_revision = '2ebb030945e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('topic_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_chat_messages_topic_id_topics', 'topics', ['topic_id'], ['id'])

    with op.batch_alter_table('study_plan_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_break', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('label', sa.String(length=120), nullable=True))
        batch_op.alter_column('topic_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study_plan_items', schema=None) as batch_op:
        batch_op.alter_column('topic_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('label')
        batch_op.drop_column('is_break')

    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_constraint('fk_chat_messages_topic_id_topics', type_='foreignkey')
        batch_op.drop_column('topic_id')

    # ### end Alembic commands ###
